export const DRAWING_SELECT = "DRAWING_SELECT";

export const DRAWING_LOAD_START = "DRAWING_LOAD_START";
export const DRAWING_LOAD_SUCCESS = "DRAWING_LOAD_SUCCESS";
export const DRAWING_LOAD_FAILURE = "DRAWING_LOAD_FAILURE";

export const DRAWING_ENUMERATE_REGIONS = "DRAWING_ENUMERATE_REGIONS";

export const COLOR_LOAD_START = "COLOR_LOAD_START";
export const COLOR_LOAD_SUCCESS = "COLOR_LOAD_SUCCESS";
export const COLOR_LOAD_FAILURE = "COLOR_LOAD_FAILURE";

export const DESIGN_CHANGE_COLOR = "DESIGN_CHANGE_COLOR";

export const DESIGN_SEND_START = "DESIGN_SEND_START";
export const DESIGN_SEND_SUCCESS = "DESIGN_SEND_SUCCESS";
export const DESIGN_SEND_FAILURE = "DESIGN_SEND_FAILURE";